
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ConnectionPoint", isSet = false )
    public class ConnectionPoint implements IASN1PreparedElement {
            
        @ASN1Element ( name = "address", isOptional =  true , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private IpAddress address = null;
                
  
        @ASN1Element ( name = "port", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private PortNumber port = null;
                
  
        
        public IpAddress getAddress () {
            return this.address;
        }

        
        public boolean isAddressPresent () {
            return this.address != null;
        }
        

        public void setAddress (IpAddress value) {
            this.address = value;
        }
        
  
        
        public PortNumber getPort () {
            return this.port;
        }

        

        public void setPort (PortNumber value) {
            this.port = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ConnectionPoint.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            