
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "IncidentLocation", isSet = false )
    public class IncidentLocation implements IASN1PreparedElement {
            
        @ASN1Element ( name = "geoLocation", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Position3D geoLocation = null;
                
  
        @ASN1Element ( name = "direction", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private PodeLaneDirection direction = null;
                
  
        @ASN1Element ( name = "area", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private Area area = null;
                
  
        @ASN1Element ( name = "roadType", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private RoadType roadType = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 20L 
		
	   )
	   
        @ASN1Element ( name = "laneCount", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private Integer laneCount = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 20L 
		
	   )
	   
        @ASN1Element ( name = "noOfLanesAffected", isOptional =  true , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
    
	private Integer noOfLanesAffected = null;
                
  
@ASN1SequenceOf( name = "lanesAffected", isSetOf = false ) 

    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 20L 
		
	   )
	   
        @ASN1Element ( name = "lanesAffected", isOptional =  true , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private java.util.Collection<IncidentLane>  lanesAffected = null;
                
  
        
        public Position3D getGeoLocation () {
            return this.geoLocation;
        }

        

        public void setGeoLocation (Position3D value) {
            this.geoLocation = value;
        }
        
  
        
        public PodeLaneDirection getDirection () {
            return this.direction;
        }

        

        public void setDirection (PodeLaneDirection value) {
            this.direction = value;
        }
        
  
        
        public Area getArea () {
            return this.area;
        }

        

        public void setArea (Area value) {
            this.area = value;
        }
        
  
        
        public RoadType getRoadType () {
            return this.roadType;
        }

        
        public boolean isRoadTypePresent () {
            return this.roadType != null;
        }
        

        public void setRoadType (RoadType value) {
            this.roadType = value;
        }
        
  
        
        public Integer getLaneCount () {
            return this.laneCount;
        }

        
        public boolean isLaneCountPresent () {
            return this.laneCount != null;
        }
        

        public void setLaneCount (Integer value) {
            this.laneCount = value;
        }
        
  
        
        public Integer getNoOfLanesAffected () {
            return this.noOfLanesAffected;
        }

        
        public boolean isNoOfLanesAffectedPresent () {
            return this.noOfLanesAffected != null;
        }
        

        public void setNoOfLanesAffected (Integer value) {
            this.noOfLanesAffected = value;
        }
        
  
        
        public java.util.Collection<IncidentLane>  getLanesAffected () {
            return this.lanesAffected;
        }

        
        public boolean isLanesAffectedPresent () {
            return this.lanesAffected != null;
        }
        

        public void setLanesAffected (java.util.Collection<IncidentLane>  value) {
            this.lanesAffected = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(IncidentLocation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            