
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeIncidentData", isSet = false )
    public class PodeIncidentData implements IASN1PreparedElement {
            
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "issueAgency", isOptional =  true , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private String issueAgency = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "eventID", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private String eventID = null;
                
  
        @ASN1Element ( name = "location", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private IncidentLocation location = null;
                
  
        @ASN1Element ( name = "event", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private IncidentEvent event = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "description", isOptional =  false , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private String description = null;
                
  
        
        public String getIssueAgency () {
            return this.issueAgency;
        }

        
        public boolean isIssueAgencyPresent () {
            return this.issueAgency != null;
        }
        

        public void setIssueAgency (String value) {
            this.issueAgency = value;
        }
        
  
        
        public String getEventID () {
            return this.eventID;
        }

        

        public void setEventID (String value) {
            this.eventID = value;
        }
        
  
        
        public IncidentLocation getLocation () {
            return this.location;
        }

        

        public void setLocation (IncidentLocation value) {
            this.location = value;
        }
        
  
        
        public IncidentEvent getEvent () {
            return this.event;
        }

        

        public void setEvent (IncidentEvent value) {
            this.event = value;
        }
        
  
        
        public String getDescription () {
            return this.description;
        }

        

        public void setDescription (String value) {
            this.description = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeIncidentData.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            