
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeDataDestination", isSet = false )
    public class PodeDataDestination implements IASN1PreparedElement {
            
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 150L 
		
	   )
	   
        @ASN1Element ( name = "speedURL", isOptional =  true , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private String speedURL = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 150L 
		
	   )
	   
        @ASN1Element ( name = "volumeURL", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private String volumeURL = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 150L 
		
	   )
	   
        @ASN1Element ( name = "occupancyURL", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private String occupancyURL = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 150L 
		
	   )
	   
        @ASN1Element ( name = "travelTimeURL", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private String travelTimeURL = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 150L 
		
	   )
	   
        @ASN1Element ( name = "weatherURL", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private String weatherURL = null;
    
    
    @ASN1String( name = "", 
            stringType =  UniversalTag.IA5String , isUCS = false )
        @ASN1ValueRangeConstraint ( 
    		
    		min = 1L, 
    		
    		max = 150L 
    		
    	   )
    	   
            @ASN1Element ( name = "incidentURL", isOptional =  true , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
        
    	private String incidentURL = null;
                
  
        
        public String getSpeedURL () {
            return this.speedURL;
        }

        
        public boolean isSpeedURLPresent () {
            return this.speedURL != null;
        }
        

        public void setSpeedURL (String value) {
            this.speedURL = value;
        }
        
  
        
        public String getVolumeURL () {
            return this.volumeURL;
        }

        
        public boolean isVolumeURLPresent () {
            return this.volumeURL != null;
        }
        

        public void setVolumeURL (String value) {
            this.volumeURL = value;
        }
        
  
        
        public String getOccupancyURL () {
            return this.occupancyURL;
        }

        
        public boolean isOccupancyURLPresent () {
            return this.occupancyURL != null;
        }
        

        public void setOccupancyURL (String value) {
            this.occupancyURL = value;
        }
        
  
        
        public String getTravelTimeURL () {
            return this.travelTimeURL;
        }

        
        public boolean isTravelTimeURLPresent () {
            return this.travelTimeURL != null;
        }
        

        public void setTravelTimeURL (String value) {
            this.travelTimeURL = value;
        }
        
  
        
        public String getWeatherURL () {
            return this.weatherURL;
        }

        
        public boolean isWeatherURLPresent () {
            return this.weatherURL != null;
        }
        

        public void setWeatherURL (String value) {
            this.weatherURL = value;
        }
        
        public String getIncidentURL () {
            return this.incidentURL;
        }

        
        public boolean isIncidentURLPresent () {
            return this.incidentURL != null;
        }
        

        public void setIncidentURL (String value) {
            this.incidentURL = value;
        }
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeDataDestination.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            