
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeLogQuery", isSet = false )
    public class PodeLogQuery implements IASN1PreparedElement {
            
        @ASN1Element ( name = "startTime", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private DDateTime startTime = null;
                
  
        @ASN1Element ( name = "endTime", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private DDateTime endTime = null;
                
  @ASN1OctetString( name = "" )
    
            @ASN1SizeConstraint ( max = 4L )
        
        @ASN1Element ( name = "requestID", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private byte[] requestID = null;
                
  @ASN1OctetString( name = "" )
    
            @ASN1SizeConstraint ( max = 4L )
        
        @ASN1Element ( name = "groupID", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private byte[] groupID = null;
                
  
        @ASN1Element ( name = "stage", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private PodeStage stage = null;
                
  
        @ASN1Element ( name = "dataType", isOptional =  true , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
    
	private PodeDataTypes dataType = null;
                
  
        @ASN1Element ( name = "dataSource", isOptional =  true , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private PodeSource dataSource = null;
                
  
        @ASN1Element ( name = "messageID", isOptional =  true , hasTag =  true, tag = 7 , hasDefaultValue =  false  )
    
	private Sha256Hash messageID = null;
                
  
        
        public DDateTime getStartTime () {
            return this.startTime;
        }

        

        public void setStartTime (DDateTime value) {
            this.startTime = value;
        }
        
  
        
        public DDateTime getEndTime () {
            return this.endTime;
        }

        
        public boolean isEndTimePresent () {
            return this.endTime != null;
        }
        

        public void setEndTime (DDateTime value) {
            this.endTime = value;
        }
        
  
        
        public byte[] getRequestID () {
            return this.requestID;
        }

        
        public boolean isRequestIDPresent () {
            return this.requestID != null;
        }
        

        public void setRequestID (byte[] value) {
            this.requestID = value;
        }
        
  
        
        public byte[] getGroupID () {
            return this.groupID;
        }

        
        public boolean isGroupIDPresent () {
            return this.groupID != null;
        }
        

        public void setGroupID (byte[] value) {
            this.groupID = value;
        }
        
  
        
        public PodeStage getStage () {
            return this.stage;
        }

        
        public boolean isStagePresent () {
            return this.stage != null;
        }
        

        public void setStage (PodeStage value) {
            this.stage = value;
        }
        
  
        
        public PodeDataTypes getDataType () {
            return this.dataType;
        }

        
        public boolean isDataTypePresent () {
            return this.dataType != null;
        }
        

        public void setDataType (PodeDataTypes value) {
            this.dataType = value;
        }
        
  
        
        public PodeSource getDataSource () {
            return this.dataSource;
        }

        
        public boolean isDataSourcePresent () {
            return this.dataSource != null;
        }
        

        public void setDataSource (PodeSource value) {
            this.dataSource = value;
        }
        
  
        
        public Sha256Hash getMessageID () {
            return this.messageID;
        }

        
        public boolean isMessageIDPresent () {
            return this.messageID != null;
        }
        

        public void setMessageID (Sha256Hash value) {
            this.messageID = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeLogQuery.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            