
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "PodeLaneType"
    )
    public class PodeLaneType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "unknown", hasTag = true , tag = 0 )
            unknown , 
            @ASN1EnumItem ( name = "offRamp", hasTag = true , tag = 1 )
            offRamp , 
            @ASN1EnumItem ( name = "onRamp", hasTag = true , tag = 2 )
            onRamp , 
            @ASN1EnumItem ( name = "normal", hasTag = true , tag = 3 )
            normal , 
            @ASN1EnumItem ( name = "shoulder", hasTag = true , tag = 4 )
            shoulder , 
            @ASN1EnumItem ( name = "left_shoulder", hasTag = true , tag = 5 )
            left_shoulder , 
            @ASN1EnumItem ( name = "left", hasTag = true , tag = 6 )
            left , 
            @ASN1EnumItem ( name = "left_center", hasTag = true , tag = 7 )
            left_center , 
            @ASN1EnumItem ( name = "center", hasTag = true , tag = 8 )
            center , 
            @ASN1EnumItem ( name = "right_center", hasTag = true , tag = 9 )
            right_center , 
            @ASN1EnumItem ( name = "right", hasTag = true , tag = 10 )
            right , 
            @ASN1EnumItem ( name = "right_shoulder", hasTag = true , tag = 11 )
            right_shoulder , 
            @ASN1EnumItem ( name = "other", hasTag = true , tag = 12 )
            other , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeLaneType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            