
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "PodeSource"
    )
    public class PodeSource implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "reserved", hasTag = true , tag = 0 )
            reserved , 
            @ASN1EnumItem ( name = "vdot", hasTag = true , tag = 1 )
            vdot , 
            @ASN1EnumItem ( name = "ritis", hasTag = true , tag = 2 )
            ritis , 
            @ASN1EnumItem ( name = "blufax", hasTag = true , tag = 3 )
            blufax , 
            @ASN1EnumItem ( name = "dms", hasTag = true , tag = 4 )
            dms , 
            @ASN1EnumItem ( name = "rtms", hasTag = true , tag = 5 )
            rtms , 
            @ASN1EnumItem ( name = "spat", hasTag = true , tag = 6 )
            spat , 
            @ASN1EnumItem ( name = "wxde", hasTag = true , tag = 7 )
            wxde , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeSource.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            