
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "GeoRegion", isSet = false )
    public class GeoRegion implements IASN1PreparedElement {
            
        @ASN1Element ( name = "nwCorner", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Position3D nwCorner = null;
                
  
        @ASN1Element ( name = "seCorner", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Position3D seCorner = null;
                
  
        
        public Position3D getNwCorner () {
            return this.nwCorner;
        }

        

        public void setNwCorner (Position3D value) {
            this.nwCorner = value;
        }
        
  
        
        public Position3D getSeCorner () {
            return this.seCorner;
        }

        

        public void setSeCorner (Position3D value) {
            this.seCorner = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GeoRegion.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            