
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeDataDelivery", isSet = false )
    public class PodeDataDelivery implements IASN1PreparedElement {
            
        @ASN1Element ( name = "podeData", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private PodeDataRecord podeData = null;
                
  
        @ASN1Element ( name = "messageID", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Sha256Hash messageID = null;
                
  
        
        public PodeDataRecord getPodeData () {
            return this.podeData;
        }

        

        public void setPodeData (PodeDataRecord value) {
            this.podeData = value;
        }
        
  
        
        public Sha256Hash getMessageID () {
            return this.messageID;
        }

        
        public boolean isMessageIDPresent () {
            return this.messageID != null;
        }
        

        public void setMessageID (Sha256Hash value) {
            this.messageID = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeDataDelivery.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            