
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeSubData", isSet = false )
    public class PodeSubData implements IASN1PreparedElement {
            
        @ASN1Element ( name = "dataElements", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private PodeDataTypes dataElements = null;
                
  
        @ASN1Element ( name = "laneDirect", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private PodeLaneDirection laneDirect = null;
                
  
        @ASN1Element ( name = "laneType", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private PodeLaneType laneType = null;
                
  
        
        public PodeDataTypes getDataElements () {
            return this.dataElements;
        }

        

        public void setDataElements (PodeDataTypes value) {
            this.dataElements = value;
        }
        
  
        
        public PodeLaneDirection getLaneDirect () {
            return this.laneDirect;
        }

        
        public boolean isLaneDirectPresent () {
            return this.laneDirect != null;
        }
        

        public void setLaneDirect (PodeLaneDirection value) {
            this.laneDirect = value;
        }
        
  
        
        public PodeLaneType getLaneType () {
            return this.laneType;
        }

        
        public boolean isLaneTypePresent () {
            return this.laneType != null;
        }
        

        public void setLaneType (PodeLaneType value) {
            this.laneType = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeSubData.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            