
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "PodeLaneDirection"
    )
    public class PodeLaneDirection implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "unknown", hasTag = true , tag = 0 )
            unknown , 
            @ASN1EnumItem ( name = "north", hasTag = true , tag = 1 )
            north , 
            @ASN1EnumItem ( name = "northEast", hasTag = true , tag = 2 )
            northEast , 
            @ASN1EnumItem ( name = "east", hasTag = true , tag = 3 )
            east , 
            @ASN1EnumItem ( name = "southEast", hasTag = true , tag = 4 )
            southEast , 
            @ASN1EnumItem ( name = "south", hasTag = true , tag = 5 )
            south , 
            @ASN1EnumItem ( name = "southWest", hasTag = true , tag = 6 )
            southWest , 
            @ASN1EnumItem ( name = "west", hasTag = true , tag = 7 )
            west , 
            @ASN1EnumItem ( name = "northWest", hasTag = true , tag = 8 )
            northWest , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeLaneDirection.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            