
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeTravelTime", isSet = false )
    public class PodeTravelTime implements IASN1PreparedElement {
            
        @ASN1Element ( name = "travelTime", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private DMinute travelTime = null;
                
  
        @ASN1Element ( name = "travelTimeAlgorithm", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private PodeTravelTimeAlgorithm travelTimeAlgorithm = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 100L 
		
	   )
	   
        @ASN1Element ( name = "travelTimeScore", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private Integer travelTimeScore = null;
                
  
        @ASN1Element ( name = "travelTimeType", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private PodeTravelTimeType travelTimeType = null;
                
  
        @ASN1Element ( name = "travelTimeDelayInfo", isOptional =  true , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
    
	private PodeTravelTimeDelayInfo travelTimeDelayInfo = null;
                
  
        
        public DMinute getTravelTime () {
            return this.travelTime;
        }

        

        public void setTravelTime (DMinute value) {
            this.travelTime = value;
        }
        
  
        
        public PodeTravelTimeAlgorithm getTravelTimeAlgorithm () {
            return this.travelTimeAlgorithm;
        }

        
        public boolean isTravelTimeAlgorithmPresent () {
            return this.travelTimeAlgorithm != null;
        }
        

        public void setTravelTimeAlgorithm (PodeTravelTimeAlgorithm value) {
            this.travelTimeAlgorithm = value;
        }
        
  
        
        public Integer getTravelTimeScore () {
            return this.travelTimeScore;
        }

        
        public boolean isTravelTimeScorePresent () {
            return this.travelTimeScore != null;
        }
        

        public void setTravelTimeScore (Integer value) {
            this.travelTimeScore = value;
        }
        
  
        
        public PodeTravelTimeType getTravelTimeType () {
            return this.travelTimeType;
        }

        
        public boolean isTravelTimeTypePresent () {
            return this.travelTimeType != null;
        }
        

        public void setTravelTimeType (PodeTravelTimeType value) {
            this.travelTimeType = value;
        }
        
  
        
        public PodeTravelTimeDelayInfo getTravelTimeDelayInfo () {
            return this.travelTimeDelayInfo;
        }

        
        public boolean isTravelTimeDelayInfoPresent () {
            return this.travelTimeDelayInfo != null;
        }
        

        public void setTravelTimeDelayInfo (PodeTravelTimeDelayInfo value) {
            this.travelTimeDelayInfo = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeTravelTime.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            