
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeTravelTimeDelayInfo", isSet = false )
    public class PodeTravelTimeDelayInfo implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 500L 
		
	   )
	   
        @ASN1Element ( name = "delay", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Integer delay = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 500L 
		
	   )
	   
        @ASN1Element ( name = "linkDelay", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Integer linkDelay = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 500L 
		
	   )
	   
        @ASN1Element ( name = "routeDelay", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private Integer routeDelay = null;
                
  
        @ASN1Element ( name = "prediction", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private PodeTravelTimeRoutePrediction prediction = null;
                
  
        
        public Integer getDelay () {
            return this.delay;
        }

        

        public void setDelay (Integer value) {
            this.delay = value;
        }
        
  
        
        public Integer getLinkDelay () {
            return this.linkDelay;
        }

        
        public boolean isLinkDelayPresent () {
            return this.linkDelay != null;
        }
        

        public void setLinkDelay (Integer value) {
            this.linkDelay = value;
        }
        
  
        
        public Integer getRouteDelay () {
            return this.routeDelay;
        }

        
        public boolean isRouteDelayPresent () {
            return this.routeDelay != null;
        }
        

        public void setRouteDelay (Integer value) {
            this.routeDelay = value;
        }
        
  
        
        public PodeTravelTimeRoutePrediction getPrediction () {
            return this.prediction;
        }

        
        public boolean isPredictionPresent () {
            return this.prediction != null;
        }
        

        public void setPrediction (PodeTravelTimeRoutePrediction value) {
            this.prediction = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeTravelTimeDelayInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            