
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeSubscriptionRequest", isSet = false )
    public class PodeSubscriptionRequest implements IASN1PreparedElement {
            
        @ASN1Element ( name = "dialogID", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private PodeDialogID dialogID = null;
                
  
        @ASN1Element ( name = "seqID", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private SemiSequenceID seqID = null;
                
  
        @ASN1Element ( name = "groupID", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private GroupID groupID = null;
                
  @ASN1OctetString( name = "" )
    
            @ASN1SizeConstraint ( max = 4L )
        
        @ASN1Element ( name = "requestID", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private byte[] requestID = null;
                
  
        @ASN1Element ( name = "type", isOptional =  false , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private PodeSubReqType type = null;
                
  
        @ASN1Element ( name = "subData", isOptional =  false , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
    
	private PodeSubData subData = null;
                
  
        @ASN1Element ( name = "protocol", isOptional =  false , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private PodeProtocol protocol = null;
                
  
        @ASN1Element ( name = "endTime", isOptional =  false , hasTag =  true, tag = 7 , hasDefaultValue =  false  )
    
	private DFullTime endTime = null;
                
  
        @ASN1Element ( name = "serviceRegion", isOptional =  true , hasTag =  true, tag = 8 , hasDefaultValue =  false  )
    
	private GeoRegion serviceRegion = null;
                
  
        
        public PodeDialogID getDialogID () {
            return this.dialogID;
        }

        

        public void setDialogID (PodeDialogID value) {
            this.dialogID = value;
        }
        
  
        
        public SemiSequenceID getSeqID () {
            return this.seqID;
        }

        

        public void setSeqID (SemiSequenceID value) {
            this.seqID = value;
        }
        
  
        
        public GroupID getGroupID () {
            return this.groupID;
        }

        

        public void setGroupID (GroupID value) {
            this.groupID = value;
        }
        
  
        
        public byte[] getRequestID () {
            return this.requestID;
        }

        

        public void setRequestID (byte[] value) {
            this.requestID = value;
        }
        
  
        
        public PodeSubReqType getType () {
            return this.type;
        }

        

        public void setType (PodeSubReqType value) {
            this.type = value;
        }
        
  
        
        public PodeSubData getSubData () {
            return this.subData;
        }

        

        public void setSubData (PodeSubData value) {
            this.subData = value;
        }
        
  
        
        public PodeProtocol getProtocol () {
            return this.protocol;
        }

        

        public void setProtocol (PodeProtocol value) {
            this.protocol = value;
        }
        
  
        
        public DFullTime getEndTime () {
            return this.endTime;
        }

        

        public void setEndTime (DFullTime value) {
            this.endTime = value;
        }
        
  
        
        public GeoRegion getServiceRegion () {
            return this.serviceRegion;
        }

        
        public boolean isServiceRegionPresent () {
            return this.serviceRegion != null;
        }
        

        public void setServiceRegion (GeoRegion value) {
            this.serviceRegion = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeSubscriptionRequest.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            