
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeLaneInfo", isSet = false )
    public class PodeLaneInfo implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 99999L 
		
	   )
	   
        @ASN1Element ( name = "zoneNum", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Integer zoneNum = null;
                
  
        @ASN1Element ( name = "laneDirection", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private PodeLaneDirection laneDirection = null;
                
  
        @ASN1Element ( name = "laneType", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private PodeLaneType laneType = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 25L 
		
	   )
	   
        @ASN1Element ( name = "laneNumber", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private Integer laneNumber = null;
                
  
        
        public Integer getZoneNum () {
            return this.zoneNum;
        }

        

        public void setZoneNum (Integer value) {
            this.zoneNum = value;
        }
        
  
        
        public PodeLaneDirection getLaneDirection () {
            return this.laneDirection;
        }

        

        public void setLaneDirection (PodeLaneDirection value) {
            this.laneDirection = value;
        }
        
  
        
        public PodeLaneType getLaneType () {
            return this.laneType;
        }

        
        public boolean isLaneTypePresent () {
            return this.laneType != null;
        }
        

        public void setLaneType (PodeLaneType value) {
            this.laneType = value;
        }
        
  
        
        public Integer getLaneNumber () {
            return this.laneNumber;
        }

        
        public boolean isLaneNumberPresent () {
            return this.laneNumber != null;
        }
        

        public void setLaneNumber (Integer value) {
            this.laneNumber = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeLaneInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            