
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Position3D", isSet = false )
    public class Position3D implements IASN1PreparedElement {
            
        @ASN1Element ( name = "lat", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Latitude lat = null;
                
  
        @ASN1Element ( name = "lon", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Longitude lon = null;
                
  
        @ASN1Element ( name = "elevation", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private Elevation elevation = null;
                
  
        
        public Latitude getLat () {
            return this.lat;
        }

        

        public void setLat (Latitude value) {
            this.lat = value;
        }
        
  
        
        public Longitude getLon () {
            return this.lon;
        }

        

        public void setLon (Longitude value) {
            this.lon = value;
        }
        
  
        
        public Elevation getElevation () {
            return this.elevation;
        }

        
        public boolean isElevationPresent () {
            return this.elevation != null;
        }
        

        public void setElevation (Elevation value) {
            this.elevation = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Position3D.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            