
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "SemiSequenceID"
    )
    public class SemiSequenceID implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "svcReq", hasTag = true , tag = 1 )
            svcReq , 
            @ASN1EnumItem ( name = "svcResp", hasTag = true , tag = 2 )
            svcResp , 
            @ASN1EnumItem ( name = "dataReq", hasTag = true , tag = 3 )
            dataReq , 
            @ASN1EnumItem ( name = "dataConf", hasTag = true , tag = 4 )
            dataConf , 
            @ASN1EnumItem ( name = "data", hasTag = true , tag = 5 )
            data , 
            @ASN1EnumItem ( name = "accept", hasTag = true , tag = 6 )
            accept , 
            @ASN1EnumItem ( name = "receipt", hasTag = true , tag = 7 )
            receipt , 
            @ASN1EnumItem ( name = "subscriptionReq", hasTag = true , tag = 8 )
            subscriptionReq , 
            @ASN1EnumItem ( name = "subscriptinoResp", hasTag = true , tag = 9 )
            subscriptinoResp , 
            @ASN1EnumItem ( name = "subscriptionCancel", hasTag = true , tag = 10 )
            subscriptionCancel
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SemiSequenceID.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            