
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "IncidentLane", isSet = false )
    public class IncidentLane implements IASN1PreparedElement {
            
        @ASN1Element ( name = "laneType", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private PodeLaneType laneType = null;
                
  
        @ASN1Element ( name = "direction", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private PodeLaneDirection direction = null;
                
  
        @ASN1Element ( name = "status", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private LaneStatus status = null;
                
  
        
        public PodeLaneType getLaneType () {
            return this.laneType;
        }

        

        public void setLaneType (PodeLaneType value) {
            this.laneType = value;
        }
        
  
        
        public PodeLaneDirection getDirection () {
            return this.direction;
        }

        

        public void setDirection (PodeLaneDirection value) {
            this.direction = value;
        }
        
  
        
        public LaneStatus getStatus () {
            return this.status;
        }

        

        public void setStatus (LaneStatus value) {
            this.status = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(IncidentLane.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            