
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "IpAddress" )
    public class IpAddress implements IASN1PreparedElement {
            
        @ASN1Element ( name = "ipv4Address", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private IPv4Address ipv4Address = null;
                
  
        @ASN1Element ( name = "ipv6Address", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private IPv6Address ipv6Address = null;
                
  
        
        public IPv4Address getIpv4Address () {
            return this.ipv4Address;
        }

        public boolean isIpv4AddressSelected () {
            return this.ipv4Address != null;
        }

        private void setIpv4Address (IPv4Address value) {
            this.ipv4Address = value;
        }

        
        public void selectIpv4Address (IPv4Address value) {
            this.ipv4Address = value;
            
                    setIpv6Address(null);
                            
        }

        
  
        
        public IPv6Address getIpv6Address () {
            return this.ipv6Address;
        }

        public boolean isIpv6AddressSelected () {
            return this.ipv6Address != null;
        }

        private void setIpv6Address (IPv6Address value) {
            this.ipv6Address = value;
        }

        
        public void selectIpv6Address (IPv6Address value) {
            this.ipv6Address = value;
            
                    setIpv4Address(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(IpAddress.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            