
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeDataElementList", isSet = false )
    public class PodeDataElementList implements IASN1PreparedElement {
            
        @ASN1Element ( name = "speed", isOptional =  true , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Speed speed = null;
                
  @ASN1Integer( name = "" )
    //@ASN1ValueRangeConstraint (
	//
	//	min = 1L,
	//
	//	max = 100L
	//
    // )
	   
        @ASN1Element ( name = "occupancy", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Integer occupancy = null;
                
  @ASN1Integer( name = "" )
//    @ASN1ValueRangeConstraint (
//
//		min = 1L,
//
//		max = 2500L
//
//	   )
	   
        @ASN1Element ( name = "volume", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private Integer volume = null;
                
  
        @ASN1Element ( name = "travelTimeInfo", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private PodeTravelTime travelTimeInfo = null;
                
  
        
        public Speed getSpeed () {
            return this.speed;
        }

        
        public boolean isSpeedPresent () {
            return this.speed != null;
        }
        

        public void setSpeed (Speed value) {
            this.speed = value;
        }
        
  
        
        public Integer getOccupancy () {
            return this.occupancy;
        }

        
        public boolean isOccupancyPresent () {
            return this.occupancy != null;
        }
        

        public void setOccupancy (Integer value) {
            this.occupancy = value;
        }
        
  
        
        public Integer getVolume () {
            return this.volume;
        }

        
        public boolean isVolumePresent () {
            return this.volume != null;
        }
        

        public void setVolume (Integer value) {
            this.volume = value;
        }
        
  
        
        public PodeTravelTime getTravelTimeInfo () {
            return this.travelTimeInfo;
        }

        
        public boolean isTravelTimeInfoPresent () {
            return this.travelTimeInfo != null;
        }
        

        public void setTravelTimeInfo (PodeTravelTime value) {
            this.travelTimeInfo = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeDataElementList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            