
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeArchiveData", isSet = false )
    public class PodeArchiveData implements IASN1PreparedElement {
            
        @ASN1Element ( name = "dateStamp", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private DDateTime dateStamp = null;
                
  
        @ASN1Element ( name = "dataType", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private PodeDataTypes dataType = null;
                
  
        @ASN1Element ( name = "geoRegion", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private GeoRegion geoRegion = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "podeData", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private byte[] podeData = null;
                
  
        
        public DDateTime getDateStamp () {
            return this.dateStamp;
        }

        

        public void setDateStamp (DDateTime value) {
            this.dateStamp = value;
        }
        
  
        
        public PodeDataTypes getDataType () {
            return this.dataType;
        }

        

        public void setDataType (PodeDataTypes value) {
            this.dataType = value;
        }
        
  
        
        public GeoRegion getGeoRegion () {
            return this.geoRegion;
        }

        

        public void setGeoRegion (GeoRegion value) {
            this.geoRegion = value;
        }
        
  
        
        public byte[] getPodeData () {
            return this.podeData;
        }

        

        public void setPodeData (byte[] value) {
            this.podeData = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeArchiveData.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            