
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeReplayData", isSet = false )
    public class PodeReplayData implements IASN1PreparedElement {
            
        @ASN1Element ( name = "startTime", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private DFullTime startTime = null;
                
  
        @ASN1Element ( name = "endTIme", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private DFullTime endTIme = null;
                
  
        
        public DFullTime getStartTime () {
            return this.startTime;
        }

        

        public void setStartTime (DFullTime value) {
            this.startTime = value;
        }
        
  
        
        public DFullTime getEndTIme () {
            return this.endTIme;
        }

        
        public boolean isEndTImePresent () {
            return this.endTIme != null;
        }
        

        public void setEndTIme (DFullTime value) {
            this.endTIme = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeReplayData.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            