
package com.leidos.ode.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PodeDataRecord", isSet = false )
    public class PodeDataRecord implements IASN1PreparedElement {
            
        @ASN1Element ( name = "source", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private PodeSource source = null;
                
  
        @ASN1Element ( name = "lastupdatetime", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private DDateTime lastupdatetime = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 60L 
		
	   )
	   
        @ASN1Element ( name = "measduration", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private Integer measduration = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "routename", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private String routename = null;
                
  
        
    @ASN1PreparedElement
    @ASN1Choice ( name = "podeData" )
    public static class PodeDataChoiceType implements IASN1PreparedElement {
            
        @ASN1Element ( name = "weather", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private PodeWeatherinfo weather = null;
                
  
        @ASN1Element ( name = "detector", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private PodeDetectorData detector = null;
                
  
        @ASN1Element ( name = "spatMap", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private PodeSpatMap spatMap = null;
                
  
        @ASN1Element ( name = "incident", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private PodeIncidentData incident = null;
                
  
        
        public PodeWeatherinfo getWeather () {
            return this.weather;
        }

        public boolean isWeatherSelected () {
            return this.weather != null;
        }

        private void setWeather (PodeWeatherinfo value) {
            this.weather = value;
        }

        
        public void selectWeather (PodeWeatherinfo value) {
            this.weather = value;
            
                    setDetector(null);
                
                    setSpatMap(null);
                
                    setIncident(null);
                            
        }

        
  
        
        public PodeDetectorData getDetector () {
            return this.detector;
        }

        public boolean isDetectorSelected () {
            return this.detector != null;
        }

        private void setDetector (PodeDetectorData value) {
            this.detector = value;
        }

        
        public void selectDetector (PodeDetectorData value) {
            this.detector = value;
            
                    setWeather(null);
                
                    setSpatMap(null);
                
                    setIncident(null);
                            
        }

        
  
        
        public PodeSpatMap getSpatMap () {
            return this.spatMap;
        }

        public boolean isSpatMapSelected () {
            return this.spatMap != null;
        }

        private void setSpatMap (PodeSpatMap value) {
            this.spatMap = value;
        }

        
        public void selectSpatMap (PodeSpatMap value) {
            this.spatMap = value;
            
                    setWeather(null);
                
                    setDetector(null);
                
                    setIncident(null);
                            
        }

        
  
        
        public PodeIncidentData getIncident () {
            return this.incident;
        }

        public boolean isIncidentSelected () {
            return this.incident != null;
        }

        private void setIncident (PodeIncidentData value) {
            this.incident = value;
        }

        
        public void selectIncident (PodeIncidentData value) {
            this.incident = value;
            
                    setWeather(null);
                
                    setDetector(null);
                
                    setSpatMap(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_PodeDataChoiceType;
        }

        private static IASN1PreparedElementData preparedData_PodeDataChoiceType = CoderFactory.getInstance().newPreparedElementData(PodeDataChoiceType.class);

    }

                
        @ASN1Element ( name = "podeData", isOptional =  false , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private PodeDataChoiceType podeData = null;
                
  
        
        public PodeSource getSource () {
            return this.source;
        }

        

        public void setSource (PodeSource value) {
            this.source = value;
        }
        
  
        
        public DDateTime getLastupdatetime () {
            return this.lastupdatetime;
        }

        

        public void setLastupdatetime (DDateTime value) {
            this.lastupdatetime = value;
        }
        
  
        
        public Integer getMeasduration () {
            return this.measduration;
        }

        
        public boolean isMeasdurationPresent () {
            return this.measduration != null;
        }
        

        public void setMeasduration (Integer value) {
            this.measduration = value;
        }
        
  
        
        public String getRoutename () {
            return this.routename;
        }

        
        public boolean isRoutenamePresent () {
            return this.routename != null;
        }
        

        public void setRoutename (String value) {
            this.routename = value;
        }
        
  
        
        public PodeDataChoiceType getPodeData () {
            return this.podeData;
        }

        

        public void setPodeData (PodeDataChoiceType value) {
            this.podeData = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PodeDataRecord.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            